name: Build Kivy APK

on:
  push:
    branches:
      - main  # Change to your default branch if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.3'  # Specify your Python version

      - name: Install Buildozer and dependencies
        run: |
          sudo apt update
          sudo apt install -y python==3.11.3-pip
          pip install buildozer
          pip install kivy kivymd  # Include other dependencies as needed

      - name: Build APK
        run: |
          buildozer -v android debug
          # You can customize this command as needed

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: my_kivy_app
          path: bin/*.apk  # Adjust if necessary
